### ISSUE TITLE
能否增加Little Tips自身快捷键设定

### ISSUE THREAD

**Issue by komazhou** [chenjing1294/Little-Tips#1]
默认的快捷键Ctrl+`与常用的Ditto的快捷键冲突，如果能够自定义快捷键，或通过长按某键来触发就更灵活了

**Comment by chenjing1294** [comment]
新版本已经支持了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenjing1294/Little-Tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenjing1294/Little-Tips] 能否增加Little Tips自身快捷键设定 (Issue #1)





 
默认的快捷键Ctrl+`与常用的Ditto的快捷键冲突，如果能够自定义快捷键，或通过长按某键来触发就更灵活了

**Comment by komazhou** [comment]
哦，我昨天是下载了便携版64位的，打开后提示无法注册热键，就无法启动，我刚刚关闭ditto之后打开没问题了，

**Comment by 7peanuts** [comment]
软件支持列表能编辑吗？直接打开更改快捷键就行了吧？
要是添加其它软件的话怎么添加呢

**Comment by chenjing1294** [comment]
直接编辑安装目录下的快捷键json文件即可。新的软件可以参考官网教程。欢迎进群讨论




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenjing1294/Little-Tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenjing1294/Little-Tips] 能否增加Little Tips自身快捷键设定 (Issue #1)





 
软件支持列表能编辑吗？直接打开更改快捷键就行了吧？
 要是添加其它软件的话怎么添加呢
