### ISSUE TITLE
是否有linux版本

### ISSUE THREAD

**Issue by Shuimuxiaochao** [chenjing1294/Little-Tips#2]
已从Windows转入deepin，是否有linux支持版本

**Comment by chenjing1294** [comment]
暂时没有开发计划




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenjing1294/Little-Tips"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 上午10:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenjing1294/Little-Tips] 是否有linux版本 (Issue #2)





 
已从Windows转入deepin，是否有linux支持版本
