### ISSUE TITLE
Project is missing MainWindow.xaml.cs file

### ISSUE THREAD

**Issue by michaelcowan** [chenjing1294/Little-Tips#3]
The project cannot be compiled because `MainWindow.xaml.cs` is missing, probably because it is included in [`.gitignore`](https://github.com/chenjing1294/Little-Tips/blob/main/.gitignore#L10)

**Comment by chenjing1294** [comment]
[dd0a7a3](https://github.com/chenjing1294/Little-Tips/commit/dd0a7a35d6fdddb94098be8bf0a49a8d023f8796)
